CREATE TABLE users (
    username VARCHAR(50) PRIMARY KEY,
    password TEXT NOT NULL
);

CREATE TABLE habits (
    id SERIAL PRIMARY KEY,
    habit_name TEXT NOT NULL,
    weekly_count INTEGER CHECK (weekly_count >= 0) DEFAULT 0,
    weekly_goal INTEGER CHECK (weekly_goal >= 0) NOT NULL,
    total_count INTEGER CHECK (total_count >= 0) DEFAULT 0,
    username VARCHAR(50) NOT NULL
        REFERENCES users ON DELETE CASCADE
);

CREATE TABLE weeks (
    username VARCHAR(50) NOT NULL
        REFERENCES users ON DELETE CASCADE,
    habit_id INTEGER
        REFERENCES habits ON DELETE CASCADE,
    FOREIGN KEY (username, habit_id),
    week_1 INTEGER DEFAULT NULL,
    week_2 INTEGER DEFAULT NULL,
    week_3 INTEGER DEFAULT NULL,
    week_4 INTEGER DEFAULT NULL,
    week_5 INTEGER DEFAULT NULL,
    week_6 INTEGER DEFAULT NULL,
    week_7 INTEGER DEFAULT NULL,
    week_8 INTEGER DEFAULT NULL,
    week_9 INTEGER DEFAULT NULL,
    week_10 INTEGER DEFAULT NULL,
    week_11 INTEGER DEFAULT NULL,
    week_12 INTEGER DEFAULT NULL,
    week_13 INTEGER DEFAULT NULL,
    week_14 INTEGER DEFAULT NULL,
    week_15 INTEGER DEFAULT NULL,
    week_16 INTEGER DEFAULT NULL,
    week_17 INTEGER DEFAULT NULL,
    week_18 INTEGER DEFAULT NULL,
    week_19 INTEGER DEFAULT NULL,
    week_20 INTEGER DEFAULT NULL,
    week_21 INTEGER DEFAULT NULL,
    week_22 INTEGER DEFAULT NULL,
    week_23 INTEGER DEFAULT NULL,
    week_24 INTEGER DEFAULT NULL,
    week_25 INTEGER DEFAULT NULL,
    week_26 INTEGER DEFAULT NULL,
    week_27 INTEGER DEFAULT NULL,
    week_28 INTEGER DEFAULT NULL,
    week_29 INTEGER DEFAULT NULL,
    week_30 INTEGER DEFAULT NULL,
    week_31 INTEGER DEFAULT NULL,
    week_32 INTEGER DEFAULT NULL,
    week_33 INTEGER DEFAULT NULL,
    week_34 INTEGER DEFAULT NULL,
    week_35 INTEGER DEFAULT NULL,
    week_36 INTEGER DEFAULT NULL,
    week_37 INTEGER DEFAULT NULL,
    week_38 INTEGER DEFAULT NULL,
    week_39 INTEGER DEFAULT NULL,
    week_40 INTEGER DEFAULT NULL,
    week_41 INTEGER DEFAULT NULL,
    week_42 INTEGER DEFAULT NULL,
    week_43 INTEGER DEFAULT NULL,
    week_44 INTEGER DEFAULT NULL,
    week_45 INTEGER DEFAULT NULL,
    week_46 INTEGER DEFAULT NULL,
    week_48 INTEGER DEFAULT NULL,
    week_49 INTEGER DEFAULT NULL,
    week_50 INTEGER DEFAULT NULL,
    week_51 INTEGER DEFAULT NULL,
    week_52 INTEGER DEFAULT NULL
);